serverFiles:
  prometheus.yml:

    # A scrape configuration scraping a Node Exporter and the Prometheus server
    # itself.
    scrape_configs:
      # Scrape Prometheus itself every 10 seconds.
      - job_name: 'prometheus'
        scrape_interval: 10s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        scrape_interval: 10s
        static_configs:
          - targets: ['prometheus-node-exporter:9100']

      - job_name: 'pushprox-proxy'
        proxy_url: http://pushprox-proxy:8080/
        static_configs:
          - targets: ['prometheus-kube-state-metrics:8080']
